### ISSUE TITLE
大佬，怎么指定模型呀

### ISSUE THREAD

**Issue by KYKY548** [xbclub/BilibiliDanmuRobot#66]
这个docker版本，怎么指定chatgtp 的具体模型。

**Comment by KYKY548** [comment]
需要用gptomini或者一些符合openai输出格式的大模型，改怎么改

**Comment by xbclub** [comment]
```
roomid: 31059542
danmulen: 20
....
# 主要看下面这部分
chatgpt:
    apiurl: https://api.openai.com/v1
    apitoken: sk-xxxxxxxxx
    prompt: 你是一个机器人
    limit: true
    model: gpt-3.5-turbo
```
